//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaMa.ResourceManagment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationVersion
    {
        public int Id { get; set; }
        public System.Guid ApplicationKey { get; set; }
        public string AssemblyVersionNumber { get; set; }
        public string FileVersionNumber { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> StopSupportDate { get; set; }
        public Nullable<System.DateTime> LastUsedDate { get; set; }
        public Nullable<System.Guid> LastUsedBy { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
