//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaMa.ResourceManagment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.ApplicationVersion = new HashSet<ApplicationVersion>();
        }
    
        public System.Guid Guid { get; set; }
        public int ResourceTypeId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<ApplicationVersion> ApplicationVersion { get; set; }
        public virtual ResourceType ResourceType { get; set; }
    }
}
